# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogform3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, max_length=20)),
                ('Last_Name', models.CharField(blank=True, max_length=20)),
                ('Middle_Name', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
